updating dep

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -246,16 +246,12 @@ on:
         required: false
         type: number
         default: 70
+      secretPayloadEncrypted:
+        description: 'Encrypted JSON containing secrets'
+        required: false
+        type: string
     secrets:
-      secret1:
-        required: false
-      secret2:
-        required: false
-      secret3:
-        required: false
-      secret4:
-        required: false
-      secret5:
+      ENCRYPTION_KEY:
         required: false
 
 permissions:
@@ -288,6 +284,7 @@ jobs:
       databaseRegionInformation: ${{ steps.regions.outputs.databaseRegionInformation }}
       imageBuilderRegionInformation: ${{ steps.regions.outputs.imageBuilderRegionInformation }}
       defaultRegion: ${{ steps.regions.outputs.defaultRegion }}
+      secrets: ${{ steps.secrets.outputs.secrets }}
 
     steps:
 
@@ -301,6 +298,36 @@ jobs:
 
       - name: Fetch all tags
         run: git fetch --all --tags
+
+      - name: Validate secret input variables
+        if: ${{ inputs.secretPayloadEncrypted }}
+        run: |
+          if [[ -n "${{ inputs.secretPayloadEncrypted }}" && -z "${{ secrets.ENCRYPTION_KEY }}" ]]; then
+            echo "Error: 'encryptionKey' must be set when 'secretPayloadEncrypted' is provided."
+            exit 1
+          fi
+
+      - name: Decrypt the secret payload
+        id: secrets
+        if: ${{ inputs.secretPayloadEncrypted && secrets.ENCRYPTION_KEY }}
+        run: |
+          # Decrypt the payload
+          echo "${{ inputs.secretPayloadEncrypted }}" | openssl enc -aes-256-cbc -d -a -pass pass:${{ secrets.encryptionKey }} > secrets.json
+          
+          # Dynamically iterate over all keys in the JSON
+          for key in $(jq -r 'keys[]' secrets.json); do
+            value=$(jq -r ".\"$key\"" secrets.json)
+          
+            # Mask the value to prevent logging
+            echo "::add-mask::$value"
+          
+            # Export the key-value pair as an environment variable
+            echo "$key=$value" >> $GITHUB_ENV
+          done
+          
+          deploySecrets=$(cat secrets.json)
+
+          echo "secrets<<'EOF'"$'\n'"$deploySecrets"$'\n\'EOF\'\n' >> $GITHUB_OUTPUT
 
       - name: Account / Environment / Auto Scaling Variables
         id: account
@@ -987,6 +1014,33 @@ jobs:
 
           echo "distribution=$EXPORT_DISTRIBUTION" >> $GITHUB_ENV
           echo "distribution=$EXPORT_DISTRIBUTION" >> IMAGE-BUILDER.txt
+
+      - name: Create and replace placeholders in scripts
+        run: |
+          # Define a function to create and replace placeholders
+          replace_placeholders() {
+            local file_name="$1"
+            local file_content="$2"
+          
+            # Create the file with content
+            cat > "$file_name" <<EOF
+            $file_content
+            EOF
+            
+              # Replace placeholders dynamically
+              for key in $(printenv | grep '^SSH_PULL_KEY_' | sed 's/=.*//'); do
+                placeholder="\\\${{ secrets.${key} }}"
+                key_value="${!key}"
+                if [ -n "$key_value" ]; then
+                  sed -i "s|$placeholder|$key_value|g" "$file_name"
+                fi
+              done
+            }
+            
+            # Call the function for each file
+            replace_placeholders ./imageBuilderScriptBuild "${{ inputs.imageBuilderScriptBuild }}"
+            replace_placeholders ./imageBuilderScriptValidate "${{ inputs.imageBuilderScriptValidate }}"
+
 
       - name: Create or update image builder
         id: imageBuilder
